name: Contributor

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'please do this') && contains(fromJson('["OWNER", "COLLABORATOR", "MEMBER"]'), github.event.comment.author_association)}}
    timeout-minutes: 80
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the branch from the PR that triggered the job
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALPHA: ${{ secrets.ALPHA }}    
      - name: Checkout the branch from the PR that triggered the job
        run: echo "Hello ${{ secrets.FOO }}"

#      - name: Trigger Kubernetes Tests
#        uses: aktechlabs/nebari/.github/workflows/kubernetes_test.yaml@main
#        with:
#          pr_number: ${{ github.event.issue.number }}

  kubernetes-tests:
    name: Contributor
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'please do this') && contains(fromJson('["OWNER", "COLLABORATOR", "MEMBER"]'), github.event.comment.author_association)}}
    uses: aktechlabs/nebari/.github/workflows/kubernetes_test.yaml@release/2022.11.1
    with:
      pr_number: ${{ github.event.issue.number }}

  infracost-tests:
    name: Contributor
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'please do this') && contains(fromJson('["OWNER", "COLLABORATOR", "MEMBER"]'), github.event.comment.author_association)}}
    uses: aktechlabs/nebari/.github/workflows/infracost.yml@release/2022.11.1
    with:
      pr_number: ${{ github.event.issue.number }}

  provider-tests:
    name: Contributor
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'please do this') && contains(fromJson('["OWNER", "COLLABORATOR", "MEMBER"]'), github.event.comment.author_association)}}
    uses: aktechlabs/nebari/.github/workflows/test-provider.yaml@release/2022.11.1
    with:
      pr_number: ${{ github.event.issue.number }}
